add_newline = false
format = "$all$character"

[character]
success_symbol = "[➜](bold green)"

[package]
disabled = true

[python]
format = "via [🐍 $version $virtualenv](bold green)"
disabled = false
